// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/helper/defaultmenu.gohtml

package helper

import (
	"io"
	"strings"
)

// Defaultmenu generates templates/helper/defaultmenu.gohtml
func Defaultmenu() string {
	var _b strings.Builder
	RenderDefaultmenu(&_b)
	return _b.String()
}

// RenderDefaultmenu render templates/helper/defaultmenu.gohtml
func RenderDefaultmenu(_buffer io.StringWriter) {
	_buffer.WriteString("<li><a id=\"mymatches\" href=\"/mymatches\">My Matches</a></li>\n<li><a id=\"match_create\" href=\"/match/create\">Create a Match</a></li>\n<li><a id=\"myteams\" href=\"/myteams\">My Teams</a></li>\n<li><a id=\"team_create\" href=\"/team/create\">Create a Team</a></li>\n<li><a id=\"myservers\" href=\"/myservers\">My Servers</a></li>\n<li><a id=\"server_create\" href=\"/server/create\">Add a Server</a></li>\n<li><a href=\"/logout\">Logout</a></li>")

}
