version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/
        target: /go/src
    networks:
      - backend_network

  db:
    container_name: db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./docker/db/.env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  backend_network:
    external: false