CREATE TABLE `matches` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `user_id` VARCHAR(36) NOT NULL,
  `server_id` VARCHAR(36) NOT NULL,
  `team1_id` VARCHAR(36) NOT NULL,
  `team2_id` VARCHAR(36) NOT NULL,
  `winner` VARCHAR(36) DEFAULT NULL,
  `cancelled` BOOLEAN NOT NULL DEFAULT FALSE,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `max_maps` TINYINT NOT NULL,
  `title` varchar(60) NOT NULL,
  `skip_veto` BOOLEAN NOT NULL,
  `api_key` varchar(32) NOT NULL,
  `team1_score` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `team2_score` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `forfeit` BOOLEAN DEFAULT NULL,
  `status` TINYINT NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES users(`id`),
  FOREIGN KEY (`server_id`) REFERENCES game_servers(`id`),
  FOREIGN KEY (`team1_id`) REFERENCES teams(`id`),
  FOREIGN KEY (`team2_id`) REFERENCES teams(`id`),
  FOREIGN KEY (`winner`) REFERENCES teams(`id`)
);