CREATE TABLE `player_stats` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `match_id` BIGINT NOT NULL,
  `map_id` BIGINT NOT NULL,
  `team_id` BIGINT NOT NULL,
  `steam_id` varchar(40) NOT NULL,
  `name` varchar(40) NOT NULL,
  `kills` int(11) NOT NULL,
  `deaths` int(11) NOT NULL,
  `roundsplayed` int(11) NOT NULL,
  `assists` int(11) NOT NULL,
  `flashbang_assists` int(11) NOT NULL,
  `teamkills` int(11) NOT NULL,
  `suicides` int(11) NOT NULL,
  `headshot_kills` int(11) NOT NULL,
  `damage` int(11) NOT NULL,
  `bomb_plants` int(11) NOT NULL,
  `bomb_defuses` int(11) NOT NULL,
  `v1` int(11) NOT NULL,
  `v2` int(11) NOT NULL,
  `v3` int(11) NOT NULL,
  `v4` int(11) NOT NULL,
  `v5` int(11) NOT NULL,
  `k1` int(11) NOT NULL,
  `k2` int(11) NOT NULL,
  `k3` int(11) NOT NULL,
  `k4` int(11) NOT NULL,
  `k5` int(11) NOT NULL,
  `firstdeath_Ct` int(11) NOT NULL,
  `firstdeath_t` int(11) NOT NULL,
  `firstkill_ct` int(11) NOT NULL,
  `firstkill_t` int(11) NOT NULL,
  FOREIGN KEY (`match_id`) REFERENCES matches(`id`),
  FOREIGN KEY (`map_id`) REFERENCES map_stats(`id`),
  FOREIGN KEY (`team_id`) REFERENCES teams(`id`)
);