// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/home.gohtml

package templates

import (
	"github.com/FlowingSPDG/get5-web-go/src/models"
	"github.com/FlowingSPDG/get5-web-go/templates/helper"
	"github.com/FlowingSPDG/get5-web-go/templates/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Home generates templates/home.gohtml
func Home(u *models.UserData) string {
	var _b strings.Builder
	RenderHome(&_b, u)
	return _b.String()
}

// RenderHome render templates/home.gohtml
func RenderHome(_buffer io.StringWriter, u *models.UserData) {

	_body := func(_buffer io.StringWriter) {
		_buffer.WriteString((helper.Header()))
		_buffer.WriteString((helper.Msg(u)))

	}

	_title := func(_buffer io.StringWriter) {

		_buffer.WriteString("<title>")
		_buffer.WriteString(gorazor.HTMLEscape(u.Name))
		_buffer.WriteString("'s homepage</title>")

	}

	_side := func(_buffer io.StringWriter) {

		_buffer.WriteString("<p>")
		_buffer.WriteString(gorazor.HTMLEscape(u.Name))
		_buffer.WriteString(" has ")
		_buffer.WriteString(gorazor.HTMLEscape(totalMessage))
		_buffer.WriteString(" messages</p>")

	}

	layout.RenderBase(_buffer, _body, _title, _side)
}
