// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/team.gohtml

package templates

import (
	"github.com/FlowingSPDG/get5-web-go/src/models"
	"github.com/FlowingSPDG/get5-web-go/templates/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Team generates templates/team.gohtml
func Team(u *models.TeamPageData) string {
	var _b strings.Builder
	RenderTeam(&_b, u)
	return _b.String()
}

// RenderTeam render templates/team.gohtml
func RenderTeam(_buffer io.StringWriter, u *models.TeamPageData) {

	_body := func(_buffer io.StringWriter) {

	}

	_menu := func(_buffer io.StringWriter) {
		if u.LoggedIn == true {

			_buffer.WriteString("<li><a id=\"mymatches\" href=\"/mymatches\">My Matches</a></li>")

			_buffer.WriteString("<li><a id=\"match_create\" href=\"/match/create\">Create a Match</a></li>")

			_buffer.WriteString("<li><a id=\"myteams\" href=\"/myteams\">My Teams</a></li>")

			_buffer.WriteString("<li><a id=\"team_create\" href=\"/team/create\">Create a Team</a></li>")

			_buffer.WriteString("<li><a id=\"myservers\" href=\"/myservers\">My Servers</a></li>")

			_buffer.WriteString("<li><a id=\"server_create\" href=\"/server/create\">Add a Server</a></li>")

			_buffer.WriteString("<li><a href=\"/logout\">Logout</a></li>")

		} else {

			_buffer.WriteString("<li><a href=\"/login\"><img src=\"/static/img/login_small.png\" height=\"18\"/></a></li>")

		}
	}

	_content := func(_buffer io.StringWriter) {

		_buffer.WriteString("<div id=\"content\">\n\t\t\n\t\t\t")
		if u.IsYourTeam == true {

			_buffer.WriteString("<h1> Your teams </h1>")

		} else {

			_buffer.WriteString("<h1> Teams for <a href=\"/user/{{ owner.id }}\"> {{ owner.name }}</a> </h1>")

		}
		_buffer.WriteString("\n  \t<ul class=\"list-group\">\n\n\t")
		if len(u.Teams) == 0 {

			_buffer.WriteString("<li class=\"list-group-item\">No teams found.</li>")

		}
		_buffer.WriteString("\n\n\t")
		for i := 0; i < len(u.Teams); i++ {
			n := u.Teams[i]

			_buffer.WriteString("<li class=\"list-group-item\">\n\t\t\t<a href=\"{{/* team.get_url() */}}\" class=\"col-sm-offset-1\"> ")
			_buffer.WriteString(gorazor.HTMLEscape(n.Name))
			_buffer.WriteString(" </a>\n\t  \t</li>")

		}
		_buffer.WriteString("\n  </ul>\n</div>")

	}

	layout.RenderBase(_buffer, _body, _menu, _content)
}
