// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/teams.gohtml

package templates

import (
	db "github.com/FlowingSPDG/get5-web-go/src/db"
	util "github.com/FlowingSPDG/get5-web-go/src/util"
	"github.com/FlowingSPDG/get5-web-go/templates/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Teams generates templates/teams.gohtml
func Teams(u *db.TeamsPageData) string {
	var _b strings.Builder
	RenderTeams(&_b, u)
	return _b.String()
}

// RenderTeams render templates/teams.gohtml
func RenderTeams(_buffer io.StringWriter, u *db.TeamsPageData) {

	_body := func(_buffer io.StringWriter) {

	}

	_menu := func(_buffer io.StringWriter) {
		if u.LoggedIn == true {

			_buffer.WriteString("<li><a id=\"mymatches\" href=\"/mymatches\">My Matches</a></li>")

			_buffer.WriteString("<li><a id=\"match_create\" href=\"/match/create\">Create a Match</a></li>")

			_buffer.WriteString("<li><a id=\"myteams\" href=\"/myteams\">My Teams</a></li>")

			_buffer.WriteString("<li><a id=\"team_create\" href=\"/team/create\">Create a Team</a></li>")

			_buffer.WriteString("<li><a id=\"myservers\" href=\"/myservers\">My Servers</a></li>")

			_buffer.WriteString("<li><a id=\"server_create\" href=\"/server/create\">Add a Server</a></li>")

			_buffer.WriteString("<li><a href=\"/logout\">Logout</a></li>")

		} else {

			_buffer.WriteString("<li><a href=\"/login\"><img src=\"/static/img/login_small.png\" height=\"18\"/></a></li>")

		}
	}

	_content := func(_buffer io.StringWriter) {

		_buffer.WriteString("<div id=\"content\">\n\t\t\t")
		if u.IsYourTeam == true {

			_buffer.WriteString("<h1> Your teams </h1>")

		} else {

			_buffer.WriteString("<h1> Teams for <a href=\"/user/")
			_buffer.WriteString(gorazor.HTMLEscInt(u.User.ID))
			_buffer.WriteString("\"> ")
			_buffer.WriteString(gorazor.HTMLEscStr(u.User.Name))
			_buffer.WriteString(" </a> </h1>")

		}
		_buffer.WriteString("\n  \t<ul class=\"list-group\">\n\n\t")
		if len(u.Teams) == 0 {

			_buffer.WriteString("<li class=\"list-group-item\">No teams found.</li>")

		}
		_buffer.WriteString("\n\n\t")
		for i := 0; i < len(u.Teams); i++ {
			n := u.Teams[i]

			_buffer.WriteString("<li class=\"list-group-item\">\n\t\t\t<a href=\"/team/")
			_buffer.WriteString(gorazor.HTMLEscInt(n.ID))
			_buffer.WriteString("\" class=\"col-sm-offset-1\"> ")
			_buffer.WriteString(gorazor.HTMLEscStr(n.Name))
			_buffer.WriteString(" </a>\n\t  \t</li>")

		}
		_buffer.WriteString("\n  </ul>\n</div>")

	}

	_version := func(_buffer io.StringWriter) {
		version, err := util.GetVersion()
		if err != nil {
			version = "N/A"
		}

		_buffer.WriteString("<div class=\"panel-footer text-muted\">\n      <p>\n        Powered by <a href=\"http://steampowered.com\">Steam</a> -\n        <a href=\"/metrics\">Stats</a>\n         - Version <a href=\"https://github.com/FlowingSPDG/get5-web-go\">")
		_buffer.WriteString(gorazor.HTMLEscStr(version))
		_buffer.WriteString("+</a>\n      </p>\n    </div>")

	}

	layout.RenderBase(_buffer, _body, _menu, _content, _version)
}
