// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: templates/user.gohtml

package templates

import (
	db "github.com/FlowingSPDG/get5-web-go/src/db"
	"github.com/FlowingSPDG/get5-web-go/templates/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// User generates templates/user.gohtml
func User(u *db.UserPageData) string {
	var _b strings.Builder
	RenderUser(&_b, u)
	return _b.String()
}

// RenderUser render templates/user.gohtml
func RenderUser(_buffer io.StringWriter, u *db.UserPageData) {

	_body := func(_buffer io.StringWriter) {

	}

	_menu := func(_buffer io.StringWriter) {
		if u.LoggedIn == true {

			_buffer.WriteString("<li><a id=\"mymatches\" href=\"/mymatches\">My Matches</a></li>")

			_buffer.WriteString("<li><a id=\"match_create\" href=\"/match/create\">Create a Match</a></li>")

			_buffer.WriteString("<li><a id=\"myteams\" href=\"/myteams\">My Teams</a></li>")

			_buffer.WriteString("<li><a id=\"team_create\" href=\"/team/create\">Create a Team</a></li>")

			_buffer.WriteString("<li><a id=\"myservers\" href=\"/myservers\">My Servers</a></li>")

			_buffer.WriteString("<li><a id=\"server_create\" href=\"/server/create\">Add a Server</a></li>")

			_buffer.WriteString("<li><a href=\"/logout\">Logout</a></li>")

		} else {

			_buffer.WriteString("<li><a href=\"/login\"><img src=\"/static/img/login_small.png\" height=\"18\"/></a></li>")

		}
	}

	_content := func(_buffer io.StringWriter) {

		_buffer.WriteString("<div id=\"content\">\n\n  <div class=\"panel panel-default\">\n    <div class=\"panel-heading\">User information</div>\n    <div class=\"panel-body\">\n      Name: ")
		_buffer.WriteString(gorazor.HTMLEscStr(u.User.Name))

	}
	_buffer.WriteString("<br>\n      Steam account: <a href=\"https://steamcommunity.com/profiles/")
	_buffer.WriteString(gorazor.HTMLEscStr(u.User.SteamID))
	_buffer.WriteString("\"> {u.User.SteamID}}</a> <br>\n      Teams saved: <a href=\"/teams/")
	_buffer.WriteString(gorazor.HTMLEscStr(u.User.SteamID))
	_buffer.WriteString("\"> {{displaying_user.teams.count()}}</a> <br>\n      Matches created: <a href=\"/matches/{{displaying_user.id}}\"> {{displaying_user.matches.count()}}</a> <br>\n    </div>\n  </div>\n\n  <div class=\"panel panel-default\">\n    <div class=\"panel-heading\">Recent Matches</div>\n    <div class=\"panel-body\">\n      {% for match in displaying_user.get_recent_matches() %}\n        <a href=\"/match/{{match.id}}\">#{{match.id}}</a>: {{ match.get_vs_string() }}\n        <br>\n      {% endfor %}\n    </div>\n  </div>\n\n</div>\n\n}")

	layout.RenderBase(_buffer, _body, _menu, _content)
}
