package entity

//go:generate stringer -type=MATCH_STATUS
type MATCH_STATUS int

const (
	MATCH_STATUS_UNKNOWN MATCH_STATUS = iota
	MATCH_STATUS_PENDING
	MATCH_STATUS_LIVE
	MATCH_STATUS_FINISHED
	MATCH_STATUS_CANCELLED
)
