// Code generated by "stringer -type=MATCH_STATUS"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MATCH_STATUS_UNKNOWN-0]
	_ = x[MATCH_STATUS_PENDING-1]
	_ = x[MATCH_STATUS_LIVE-2]
	_ = x[MATCH_STATUS_FINISHED-3]
	_ = x[MATCH_STATUS_CANCELLED-4]
}

const _MATCH_STATUS_name = "MATCH_STATUS_UNKNOWNMATCH_STATUS_PENDINGMATCH_STATUS_LIVEMATCH_STATUS_FINISHEDMATCH_STATUS_CANCELLED"

var _MATCH_STATUS_index = [...]uint8{0, 20, 40, 57, 78, 100}

func (i MATCH_STATUS) String() string {
	if i < 0 || i >= MATCH_STATUS(len(_MATCH_STATUS_index)-1) {
		return "MATCH_STATUS(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MATCH_STATUS_name[_MATCH_STATUS_index[i]:_MATCH_STATUS_index[i+1]]
}
